services:
  - type: web
    name: aria-webhook-proxy
    runtime: docker
    plan: standard
    envVars:
      - key: XI_API_KEY
        value: sk_1a2a2a07d19b6f993c0b98203dd355f2938c9f855ba76d97
      - key: TIMELY_EMAIL
        value: moj_b52@yahoo.com
      - key: TIMELY_PASSWORD
        value: Ariasorush12?
